#got the madlib from here -> https://www.woojr.com/mad-libs-worksheets/back-to-school-mad-libs/
adj1 = input("Enter an adjective: ")
noun1 = input("Enter a noun: ")
noun2 = input("Enter another noun: ")
verb1 = input("Enter a verb: ")
noun3 = input("Enter another noun:" )
verb2 = input("Enter another verb: ")
noun4 = input("Enter another noun: ")
noun5 = input("Enter a noun (plural): ")
noun6 = input("Enter a noun (plural): ")
noun7 = input("Enter another noun: ")
noun8 = input("Enter another noun: ")
adj2 = input("Enter another adjective: ")
noun9 = input("Enter another noun: ")
noun10 = input("Enter another noun: ")
emotion = input("Enter an emotion: ")
verb3 = input("Enter a past tense verb (-ed): ")

print("Lunchtime in our cafeteria is always " + adj1 + ".")
print("They serve hot " + noun1 + " and " + noun2 + ", but some students " + verb1 + " their own " + noun3 + " to eat. ")
print("Some kids quietly " + verb2 + " their " + noun4 + ", while others throw " + noun5 + " or " + noun6 + " when the teachers aren't looking.")
